#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════"
echo "  🚀 Living Resume API — Codespace Ready!"
echo "═══════════════════════════════════════════════"
echo ""
echo "  Quick Start:"
echo "    bun run start    ← Interactive wizard (start here!)"
echo "    bun run build    ← Parse your template to JSON"
echo "    bun run preview  ← Test your API locally"
echo "    bun run deploy   ← Ship to Cloudflare Workers"
echo ""
echo "  Need help? Check README.md"
echo "═══════════════════════════════════════════════"
echo ""
