#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════"
echo "  🚀 Living Resume API — Codespace Ready!"
echo "═══════════════════════════════════════════════"
echo ""
echo "  Two commands to go live:"
echo ""
echo "    Step 1:  bun run start    ← Build your profile"
echo "    Step 2:  bun run deploy   ← Publish your API"
echo ""
echo "  That's it! Deploy handles Cloudflare setup"
echo "  automatically the first time you run it."
echo ""
echo "  Other commands:"
echo "    bun run preview  ← Test locally before deploying"
echo "    bun run build    ← Rebuild JSON without deploying"
echo ""
echo "  Need help? Check README.md"
echo "═══════════════════════════════════════════════"
echo ""
